"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['piano_room.py']
APP_NAME = "搶琴房大作戰"
DATA_FILES = ['大耳狗.jpeg']
OPTIONS = {'includes': ['time', 'pytz', 'threading', 'tkinter', 'datetime', 'PIL', 'selenium'],
           'iconfile': '大耳狗.jpeg', 
           'plist': {
               'CFBundleName': APP_NAME,
               'CFBundleDisplayName': APP_NAME,
               'CFBundleGetInfoString': "Automated Piano Room Reservation",
               'CFBundleVersion': "1.0.0",
               'CFBundleShortVersionString': "1.0.0",
               'NSHumanReadableCopyright': u"Copyright © 2023, Yu-Jun Kuo, All Rights Reserved"
            },
        }

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
